### ISSUE TITLE
Midterm Milestone

### ISSUE THREAD

**Issue by allisonkoh** [allisonkoh/dash-reddit-trp#8]
Allison Tasks 

- [x] Scrape additional feed: `r/MensRights`
- [x] Topic models + viz with `PyLDAvis`
- [x] Create clean notebook 
- [x] Add descriptions for visualizations in the notebook 
- [x] Written: (1) Second half of progress section (visualizing topic models) (2) Future work 

Sam Tasks 

- [x] Add basic viz from `r/MensRights` scraped feed to notebook 
- [x] Written: (1) Rewrite task section to reflect our current task (based on what we wrote in our research proposal- shown in line)  (2) First half of progress section (generating the basic visualizations on number of comments and scores, what questions those answer)
